name: Documentation
description: Report missing, outdated, or unclear documentation
title: "[Docs]: "
labels: [ documentation ]
body:
- type: markdown
  attributes:
    value: Noticed an issue with the documentation? Let us know!

- type: textarea
  id: description
  attributes:
    label: Describe the Issue
    description: What part of the documentation needs updating or improvement?
  validations:
    required: true

- type: textarea
  id: current_state
  attributes:
    label: Current State
    description: Summarize how the documentation currently describes the topic.

- type: textarea
  id: improvements
  attributes:
    label: Suggested Improvements
    description: What needs to be added, removed, or clarified?
  validations:
    required: false

- type: textarea
  id: additional
  attributes:
    label: Additional Context
    description: Any references, screenshots, or other context that helps understand the issue.
